sudo: required
dist: trusty
language: php
php:
  - 7.4snapshot

addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
    - libxml2-utils

branches:
  only:
    - master

env:
  global:
    - DB=mysql
    - CORE_BRANCH=master
    - PHP_COVERAGE=FALSE
    - TEST_SUITE=LINT-PHP

cache:
  directories:
    - "$HOME/.composer/cache/files"
    - "$HOME/.npm"

before_install:
  - php --info
  # Setup MySQL if applicable
  - if [[ "$DB" == 'mysql' ]]; then mysql -u root -e 'create database oc_autotest;'; fi
  - if [[ "$DB" == 'mysql' ]]; then mysql -u root -e "CREATE USER 'oc_autotest'@'localhost' IDENTIFIED BY '';"; fi
  - if [[ "$DB" == 'mysql' ]]; then mysql -u root -e "grant all on oc_autotest.* to 'oc_autotest'@'localhost';"; fi
  # set up nextcloud
  - composer self-update
  - cd ..
  - git clone https://github.com/nextcloud/server.git --recursive --depth 1 -b $CORE_BRANCH core
  - mv calendar core/apps/

before_script:
  - cd core/apps/calendar

  # XDebug is only needed if we report coverage -> speeds up other builds
  - if [[ "$PHP_COVERAGE" = "FALSE" ]]; then phpenv config-rm xdebug.ini || true; fi

script:
  # Run server's app code checker
  - sh -c "if [ '$TEST_SUITE' = 'LINT-PHP' ]; then php ../../occ app:check-code calendar; fi"

  # Run PHP tests
  - if [[ "$PHP_COVERAGE" = "TRUE" ]]; then wget https://scrutinizer-ci.com/ocular.phar;
    fi
  - if [[ "$PHP_COVERAGE" = "TRUE" ]]; then php ocular.phar code-coverage:upload --format=php-clover
    tests/clover.xml; fi

  # Test packaging
  - if [[ "$TEST_SUITE" = "PACKAGE" ]]; then make dev-setup; fi
  - if [[ "$TEST_SUITE" = "PACKAGE" ]]; then make build-js-production; fi
  - if [[ "$TEST_SUITE" = "PACKAGE" ]]; then make appstore; fi
